// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7dLQ-mGM8RlWTm_6Toj5-aYz2a82x8Ho',
    appId: '1:12708235353:web:9041a7ba2f8ec135810948',
    messagingSenderId: '12708235353',
    projectId: 'chatapp-d972c',
    authDomain: 'chatapp-d972c.firebaseapp.com',
    storageBucket: 'chatapp-d972c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRVlDeLiM6DSGJ9T-HBH7zU0rgtcO1wEw',
    appId: '1:12708235353:android:8356cf9e27bc3d88810948',
    messagingSenderId: '12708235353',
    projectId: 'chatapp-d972c',
    storageBucket: 'chatapp-d972c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBdnmiGoptbh0s1CvwdYfL60LR4esoDo',
    appId: '1:12708235353:ios:60664defb9f05fdc810948',
    messagingSenderId: '12708235353',
    projectId: 'chatapp-d972c',
    storageBucket: 'chatapp-d972c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBdnmiGoptbh0s1CvwdYfL60LR4esoDo',
    appId: '1:12708235353:ios:60664defb9f05fdc810948',
    messagingSenderId: '12708235353',
    projectId: 'chatapp-d972c',
    storageBucket: 'chatapp-d972c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7dLQ-mGM8RlWTm_6Toj5-aYz2a82x8Ho',
    appId: '1:12708235353:web:b4a4e5c82a7b08e0810948',
    messagingSenderId: '12708235353',
    projectId: 'chatapp-d972c',
    authDomain: 'chatapp-d972c.firebaseapp.com',
    storageBucket: 'chatapp-d972c.firebasestorage.app',
  );
}
